/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_serialport_api_SerialPort */

#ifndef _Included_cn_qd_peiwen_serialport_PWSerialPort
#define _Included_cn_qd_peiwen_serialport_PWSerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PWSerialPort
 * Method:    open
 */
JNIEXPORT jlong JNICALL
Java_cn_qd_peiwen_serialport_PWSerialPort_open
        (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint);
/*
 * Class:     PWSerialPort
 * Method:    read
 */
JNIEXPORT jint JNICALL
Java_cn_qd_peiwen_serialport_PWSerialPort_read
        (JNIEnv *, jobject, jlong, jbyteArray, jint);
/*
 * Class:     PWSerialPort
 * Method:    read
 */
JNIEXPORT jint JNICALL
Java_cn_qd_peiwen_serialport_PWSerialPort_write
        (JNIEnv *, jobject, jlong, jbyteArray, jint);
/*
 * Class:     PWSerialPort
 * Method:    close
 */
JNIEXPORT void JNICALL
Java_cn_qd_peiwen_serialport_PWSerialPort_close
        (JNIEnv *, jobject, jlong);
/*
 * Class:     PWSerialPort
 * Method:    writeFile
 */
JNIEXPORT void JNICALL
Java_cn_qd_peiwen_serialport_PWSerialPort_writeFile
        (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
