/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_serialport_api_SerialPort */

#ifndef _Included_cn_qd_peiwen_serialport_SerialPort
#define _Included_cn_qd_peiwen_serialport_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SerialPort
 * Method:    open
 */
JNIEXPORT jobject JNICALL Java_cn_qd_peiwen_serialport_SerialPort_open
        (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jint, jint);

/*
 * Class:     SerialPort
 * Method:    close
 */
JNIEXPORT void JNICALL Java_cn_qd_peiwen_serialport_SerialPort_writeFile
        (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     SerialPort
 * Method:    close
 */
JNIEXPORT void JNICALL Java_cn_qd_peiwen_serialport_SerialPort_close
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
